const sampleProducts = [
    {
        name: "Skinny Jeans",
        price: 899,
        description: "Comfortable skinny fit jeans made with stretchable cotton blend fabric.",
        availableSizes: ["S", "M", "L", "XL"],
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQPjt_XJhy-HVr3du_VRrSroC5CE92YEdq3XqR-ndwHzM6CHqY7NNhsJT9Ayy1JN-HkhMtOFvu3aJo2POGir4pTYYmL6SvRNsUpzGRH1owE",
        colors: ["Blue", "Black", "Grey"],
        material: "Denim",
        category: "Jeans",
    },
    {
        name: "Cargo Pants",
        price: 1299,
        description: "Trendy cargo pants with spacious pockets and relaxed fit. Great for casual wear.",
        availableSizes: ["S", "M", "L", "XL", "XXL"],
        image: "https://offduty.in/cdn/shop/files/armygreen3_page-0001_1080x.jpg?v=1706199932",
        colors: ["Army Green", "Khaki", "Black"],
        material: "Cotton Blend",
        category: "Trousers",
    },
    {
        name: "Crop Top",
        price: 599,
        description: "Trendy and stylish crop top made with soft stretchable fabric for everyday comfort.",
        availableSizes: ["XS", "S", "M", "L"],
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR9nRi4QRl3kqTvy4geudJT9PLvGd1JDF4GpzSqbPv4QlITkLscYISp4vwk-D8nWkqQ14I2AHIL933_XiJVInw6fmjWwC73fzc6GM9mNvZtOL_A-PVOda-k",
        colors: ["Pink", "Black", "White"],
        material: "Cotton Lycra",
        category: "Tops",
    },
    {
        name: "White Shirt",
        price: 999,
        description: "High-quality cotton shirt with a classic collar and modern fit. Perfect for formal and casual wear.",
        availableSizes: ["M", "L", "XL", "XXL"],
        image: "https://th.bing.com/th/id/OPAC.JfPC6qGCLIaS3Q474C474?w=592&h=550&o=5&dpr=1.3&pid=21.1",
        colors: ["White", "Light Blue"],
        material: "100% Cotton",
        category: "Shirts",
    },
    {
        name: "Graphic T-Shirts",
        price: 749,
        description: "Comfortable Graphic T-Shirts with fine cotton fabric perfect for occasions.",
        availableSizes: ["M", "L", "XL", "XXL"],
        image: "https://images.meesho.com/images/products/172443243/1aiem_1200.jpg",
        colors: ["Maroon", "Mustard", "Green"],
        material: "Cotton Blend",
        category: "T-Shirts",
    },
    {
        name: "Button-down Shirt",
        price: 1299,
        description: "Stylish Button-down Shirt with soft fleece interior. Ideal for casual wear.",
        availableSizes: ["S", "M", "L", "XL", "XXL"],
        image: "https://images.meesho.com/images/products/502597476/fmfrc_1200.jpg",
        colors: ["Black", "Navy Blue"],
        material: "Fleece Cotton",
        category: "Shirts",
    },
    {
        name: "Denim Shorts",
        price: 699,
        description: "Trendy ripped denim shorts with raw edges. Best for casual summer outings.",
        availableSizes: ["XS", "S", "M", "L"],
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQftuGhH8iDJ98eK9rlgqJnZDTTTIvGXeZEBeHQZwA7YxishoJPJ4qBih16VCtu2vEGQJHhiVKYDBci_pFKQT6nQZiF17gCTj3RSmn73Fl0MWEKZY0__F2hYg",
        colors: ["Light Blue", "Dark Blue"],
        material: "100% Cotton Denim",
        category: "Shorts",
    },
    {
        name: "Floral Frock",
        price: 1199,
        description: "Elegant floral frock with flared hem and puff sleeves, perfect for casual or semi-formal occasions.",
        availableSizes: ["S", "M", "L"],
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRmndTXjwIaVwMpMs9pQIAfSaeKr4gFpzmuoZcSzd_q18L6OhFzANuidhGM3dGTFn7qgdXu7m1wn3v0qS5k3cjTHyyFFxEbQ7Ek5OpFxV_bXyyx1Mw2sIQB",
        colors: ["Pink", "Peach", "Sky Blue"],
        material: "Rayon",
        category: "Frocks",
    },
    {
        name: "Summer Midi",
        price: 999,
        description: "Lightweight and breezy midi dress, perfect for summer outings and vacations.",
        availableSizes: ["XS", "S", "M", "L", "XL"],
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRxO8oLUMPiM9WV9RZ4iBO9Japl6y9S1PnXud4G1u8orLDw5qnrGmKP-ZC8kPHrFxr-GDnEp4Z0NR9cQ7aoZSaVWo6aP9khN3rLEyoyN3hPr4W9HOVu-uRm",
        colors: ["Yellow", "Sky Blue", "Mint Green"],
        material: "Cotton Blend",
        category: "Midis",
    },
    {
        name: "Midi Dress",
        price: 1799,
        description: "Elegant and stylish midi dress, perfect for semi-formal and party occasions.",
        availableSizes: ["XS", "S", "M", "L", "XL"],
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQqBAt0BdGhZ0_M3OBKpGCj9WoZr1V9AcLWYUHLqn2Uu76iyOS0H7GGzlHfLQmEIVx7vs-vIz0rcGHlRSFBv_r0dSMi1wd65dvE1r7pk6EAQlkzkEZEmU9H",
        colors: ["Black", "Wine Red", "Peach"],
        material: "Georgette Blend",
        category: "Midis",
    },
    {
        name: "Mini Skirt",
        price: 599,
        description: "Trendy and stylish mini skirt made from breathable cotton blend fabric.",
        availableSizes: ["XS", "S", "M", "L"],
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTjXAT6wUkL4sTmRvX232TN4yEAJKAo9PZ5VW-979gt7JzxprMwr9M09EsW-12MDAvSfpgpkF9cqsaIrDe1xULLTca7-urVXj0MN4AFt_Z9",
        colors: ["Pink", "Blue", "Beige"],
        material: "Cotton Blend",
        category: "Skirts",
    },
    {
        name: "Formal Blazer",
        price: 1499,
        description: "Tailored formal blazer perfect for office wear and business events.",
        availableSizes: ["S", "M", "L", "XL"],
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRU81B-es-eWvmEFlfw3exxTIlUYmOe-BWin7-BHnx_Uj35cOIdhSFZEB3P6M1UIn9loL4TNijWsrPA8nJb8Qqlb5A5L2rqxEwmwDGziur74hfophc3PJ_aRw",
        colors: ["Black", "Navy Blue", "Maroon"],
        material: "Premium Cotton Blend",
        category: "Blazers",
    },
    {
        name: "Printed Kurti",
        price: 899,
        description: "Elegant printed kurti made from soft cotton, ideal for casual and ethnic wear.",
        availableSizes: ["S", "M", "L", "XL", "XXL"],
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSVVcLkA5sxwZy7_BDG1phWUi3gMwSUw7F9wn1T8hGR1BcLafNBVT1s1gFhIf-_30uEhEeb7uY1rR857Ambz2Hrm24wrzaq0XqTp7_nVpJQv8P0TlLxUKqL",
        colors: ["Maroon", "Beige", "Mustard"],
        material: "Cotton",
        category: "Kurti",
    },
    {
        name: "Wool Jacket",
        price: 1599,
        description: "Warm and stylish wool jacket with full sleeves and a classic button closure, perfect for winters.",
        availableSizes: ["M", "L", "XL"],
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTlWvTro5elj9eqXXqSP7DUyTq-OKnAS780nO48H6mLVJOthHTljfCuwaQfYcvtodAWzPWSOtVuiq-1LeSdcy8pCJvNpyD230rLxBZ8xy_4gjvntG3dNsRL",
        colors: ["Grey", "Black", "Maroon"],
        material: "Wool Blend",
        category: "Jackets",
    },
    {
        name: "Oversized Sweatshirt",
        price: 899,
        description: "Relaxed-fit oversized sweatshirt with soft fleece lining, great for casual winter wear.",
        availableSizes: ["M", "L", "XL", "XXL"],
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSE2M9gg6S0I9GMTPFubro6o9lr1PB1bhlNKwba7sgnVJYns8u_d00mnt5QqEBQpc9Ql3aq6VqVf06F0ADeq7CO5gqBREvyxGAaSiFwYYU",
        colors: ["Black", "Pink", "Lavender", "White"],
        material: "Fleece Cotton",
        category: "Sweatshirts",
    },
    {
    name: "Grey Trouser",
    price: 1696,
    description: "A stylish trousers suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://kaapus.com/cdn/shop/files/4R9A1394.jpg?v=1742218502",
    colors: ["Black", "Beige"],
    material: "Premium Fabric",
    category: "Trousers",
  },
  {
    name: "Black Jean",
    price: 927,
    description: "A stylish jeans suitable for all occasions. Made with premium fabric.",
    availableSizes: ["30", "32", "34", "36"],
    image: "https://www.urbanofashion.com/cdn/shop/files/jeanlstowl-black-1.jpg?v=1719194107",
    colors: ["Black", "Blue"],
    material: "Premium Fabric",
    category: "Jeans",
  },
  {
    name: "Green Kurti",
    price: 904,
    description: "A stylish kurti suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://gunjfashion.com/cdn/shop/products/designer-green-rayon-embroidered-indian-kurti_1.jpg?v=1678804122",
    colors: ["Orange", "Green"],
    material: "Premium Fabric",
    category: "Kurti",
  },
  {
    name: "Red Gown",
    price: 344,
    description: "A stylish gowns suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM5ruzy2QRaNtWKm3S2Raz66At8_jWr1x0ww&s",
    colors: ["Red", "Peach"],
    material: "Premium Fabric",
    category: "Gowns",
  },
  {
    name: "Black Hoodie",
    price: 961,
    description: "A stylish hoodies suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L", "XL"],
    image: "https://caslay.in/cdn/shop/files/4M6A0227.jpg?v=1728708874&width=1946",
    colors: ["Navy", "Maroon"],
    material: "Premium Fabric",
    category: "Hoodies",
  },
  {
    name: "Orange Kurti",
    price: 2897,
    description: "A stylish kurti suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPJx_PK_vecCZGnCmatiAacr8veYjh-uS8Rg&s",
    colors: ["Orange", "Green"],
    material: "Premium Fabric",
    category: "Kurti",
  },
  {
    name: "Pink Lehenga",
    price: 1943,
    description: "A stylish lehengas suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L"],
    image: "https://devalstore.in/cdn/shop/files/4515-4_1024x1024_5772e6ad-c88d-4bb3-85cf-33b6c4833dbd.webp?v=1709895913",
    colors: ["Maroon", "Pink"],
    material: "Premium Fabric",
    category: "Lehengas",
  },
  {
    name: "Maroon Lehenga",
    price: 1982,
    description: "A stylish lehengas suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L"],
    image: "https://img.perniaspopupshop.com/catalog/product/a/n/ANNUSC092406_1.jpg?impolicy=detailimageprod",
    colors: ["Golden", "Maroon"],
    material: "Premium Fabric",
    category: "Lehengas",
  },
  {
    name: "Green Shirt",
    price: 435,
    description: "A stylish shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://spykar.com/cdn/shop/files/gBEA4LKou8-WTPSOS2BC020-DARK-GREEN-_1.webp?v=1750337262",
    colors: ["Green", "Blue"],
    material: "Premium Fabric",
    category: "Shirts",
  },
  {
    name: "Red T-Shirt",
    price: 1716,
    description: "A stylish t-shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L", "XL"],
    image: "https://img.tatacliq.com/images/i20//437Wx649H/MP000000024238983_437Wx649H_202410271705091.jpeg",
    colors: ["Red", "White"],
    material: "Premium Fabric",
    category: "T-Shirts",
  },
  {
    name: "Brown Jacket",
    price: 622,
    description: "A stylish jackets suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/14017334/2021/4/15/321644e4-48e9-4856-bf6d-fed0e05cc0721618469772639-Leather-Retail-Women-Jackets-6461618469770493-1.jpg",
    colors: ["Black", "Brown"],
    material: "Premium Fabric",
    category: "Jackets",
  },
  {
    name: "Golden Lehenga",
    price: 1475,
    description: "A stylish lehengas suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L"],
    image: "https://empress-clothing.com/cdn/shop/products/AZ-1002E.jpg?v=1628592005",
    colors: ["Pink", "Golden"],
    material: "Premium Fabric",
    category: "Lehengas",
  },
  {
    name: "Olive Jacket",
    price: 436,
    description: "A stylish jackets suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://imagescdn.vanheusenindia.com/img/app/product/9/932664-11853063.jpg?auto=format&w=390",
    colors: ["Olive", "Brown"],
    material: "Premium Fabric",
    category: "Jackets",
  },
  {
    name: "White Shirt",
    price: 2678,
    description: "A stylish shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://www.hancockfashion.com/cdn/shop/files/16111WhiteS_1.jpg?v=1734412830",
    colors: ["Green", "White"],
    material: "Premium Fabric",
    category: "Shirts",
  },
  {
    name: "Beige Trouser",
    price: 413,
    description: "A stylish trousers suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://img.tatacliq.com/images/i17//437Wx649H/MP000000022039547_437Wx649H_202405221512421.jpeg",
    colors: ["Black", "Grey"],
    material: "Premium Fabric",
    category: "Trousers",
  },
  {
    name: "White T-Shirt",
    price: 2199,
    description: "A stylish t-shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L", "XL"],
    image: "https://www.mystore.in/s/62ea2c599d1398fa16dbae0a/66b22a9d56dc0e00b127b6f6/gorgeous-womens-oversized-tshirt-white-640x640.webp",
    colors: ["Black", "White"],
    material: "Premium Fabric",
    category: "T-Shirts",
  },
  {
    name: "Yellow Kurti",
    price: 2127,
    description: "A stylish kurti suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://www.soosi.co.in/cdn/shop/products/IMG-20190327-WA0035.jpg?v=1571711108",
    colors: ["Green", "Orange"],
    material: "Premium Fabric",
    category: "Kurti",
  },
  {
    name: "Blue Jean",
    price: 563,
    description: "A stylish jeans suitable for all occasions. Made with premium fabric.",
    availableSizes: ["30", "32", "34", "36"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkEedBbbbPNxqbqq_4D2jtFS7YAfvYRA5ZNw&s",
    colors: ["Blue", "Black"],
    material: "Premium Fabric",
    category: "Jeans",
  },
  {
    name: "Peach Gown",
    price: 1609,
    description: "A stylish gowns suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L"],
    image: "https://assets.panashindia.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/3/338gw02-1048.jpg",
    colors: ["Red", "Peach"],
    material: "Premium Fabric",
    category: "Gowns",
  },
  {
    name: "Black T-Shirt",
    price: 2435,
    description: "A stylish t-shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L", "XL"],
    image: "https://muselot.in/cdn/shop/products/Plaintshirtsforwomenonline-Greyplaintshirtforwomen-Muselot_1.jpg?v=1657571397",
    colors: ["Blue", "White"],
    material: "Premium Fabric",
    category: "T-Shirts",
  },
  {
    name: "Maroon Hoodie",
    price: 457,
    description: "A stylish hoodies suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcnhKagi68X6Cg4exTiJJS6AjD8I_GxGiMXQ&s",
    colors: ["Maroon", "Navy"],
    material: "Premium Fabric",
    category: "Hoodies",
  },
  {
    name: "Blue Shirt",
    price: 2392,
    description: "A stylish shirts suitable for all occasions. Made with premium fabric.",
    availableSizes: ["M", "L", "XL"],
    image: "https://thehouseofrare.com/cdn/shop/files/IMG_0122_2f818069-6199-43a1-9e21-dbbbc6e0b526.jpg?v=1743496555",
    colors: ["Grey", "Green"],
    material: "Premium Fabric",
    category: "Shirts",
  },
  {
    name: "White Top",
    price: 841,
    description: "A stylish tops suitable for all occasions. Made with premium fabric.",
    availableSizes: ["S", "M", "L"],
    image: "https://m.media-amazon.com/images/I/818GzpAyz5L._UY1100_.jpg",
    colors: ["Pink", "Sky Blue"],
    material: "Premium Fabric",
    category: "Tops",
  }
    


];
module.exports = {data: sampleProducts};